spring:
  application:
    name: crudcliente

  datasource:
    url: jdbc:h2:mem:testorm
    username: admin
    password: "123"

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    #show-sql: true
    properties:
      hibernate:
      #  format_sql: true
server:
  port: 8080
